# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: b5cf7f53-db12-431e-bb5a-1474578cc9d6
          heroku_app_name: rona-analytics #Must be unique in Heroku
          heroku_email: danielleng510@gmail.com
          dontuseforce: 0
          procfile: 1
